--- 
title: "Resolução do livro 'Introducción a la econometría (Wooldridge)'"
author: "Igo da Costa Andrade"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# A natureza da econometria e os dados econômicos

## Exercícios com computador

1. Para este exercício, empregue a base de dados `WAGE1.RAW`.

  i) Determine o nível de educação médio da amostra. Quais são os níveis de educação mínimo e máximo?
  
  ii) Determine o salário médio por hora (*wage*) da amostra. Parece ser alto ou baixo?
  
  iii) Os dados de salários estão em dólares de 1976. Usando o *Economic Report of the President* (de 2004 ou posterior ou o Informe de Governo em países de língual espanhola) obtenha e dê os índices de preços ao consumidor (IPC) correspondentes a 1976 e 2003.
  
  iv) Use os valores dos IPC do inciso iii) para determinar o salário médio por hora em dólares de 2003. Parece agora mais razoável o salário médio por hora?
  
  v) Quantas mulheres (*females*) existem na amostra? Quantos homens?
  
  
2. Para responder estas perguntas utilize a base de dados `BWGHT.RAW`.

  i) Quantas mulheres existem na amostra (male = 0) e quantas das informantes fumaram durante a gravidez?
  
  ii) Qual é a quantidade média de cigarros consumidos por dia (cigs)? É a média, neste caso, uma medida representativa da mulher "típica"? Explique.
  
  iii) Entre as mulheres que fumaram durante a gravidez, qual é a quantidade média de cigarros consumidos por dia? Qual é a relação deste com sua resposta ao inciso ii) e por quê?
  
  iv) Determine a média de *fatheduc* (anos de educação dos pais) na amostra. Por que se empregam 1192 observações para calcular este valor médio?
  
  v) Determine a renda familiar média (*famine*) e o respectivo desvio padrão em dólares.
  
3. O dados de `MEAP01.RAW` pertencem ao estado de Michigan no ano de 2001. Empregue esses dados para responder as percuntas seguintes.

  i) Determine os valores máximo e mínimo de *math4*. É lógico este intervalo? Explique.
  
  ii) Quantas escolas têm uma taxa perfeita de aprovados no exame de matemática? A que porcentagem do total da amostra corresponde esta quantidade?
  
  iii) Em quantas escolar a taxa de aprovados em matemática é exatamente 50%?
  
  iv) Compare a média das taxas de aprovados em matemática e em leitura. Qual destas prova é mais difícil de aprovar?
  
  v) Encontre a correlação entre *math4* e *read4*? Que se conclui disso?
  
  vi) A variável *exppp* é o gasto por aluno. Determine o valor médio e o desvio padrão de *exppp*. Parece haver uma grande variação no gasto por aluno?
  
  vii) Suponha que a escola A gasta 6000 dólares por aluno e a escola B gasta 5000 dólares por aluno. Dê a porcentagem em que o gasto da escola A supera o gasto da escola B. Compare esta porcentagem com $100 \cdot \left[\log{(6000)} - \log{(5000)}\right]$, que é a diferença percentual aproximada baseada na diferença dos logarítmos naturais. 
  
4. A base de dados `JTRAIN2.RAW` provém de um experimento de capacitação para o trabalho realizado para homens com baixa renda durante 1976-1977.

  i) Use a variável indicadora *train* para determinar a proporção de homens que receberam treinamento no trabalho.
  
  ii) A variável *re78* é a renda desde 1978, dados em dólares de 1982. Determine a valor médio de *re78* para a amostra de homens que receberam a capacitação no trabalho e para a amostra de homens que não receberam. Esta diferença é economicamente grande?
  
  iii) A variável *unem78* indica se um homem esteve desempregado ou não em 1978. Que proporção de homens que receberam treinamento para o trabalho estão desempregados? E daqueles que não receberam capacitação? Comente a diferença.
  
  iv) Com base nos incisos ii) e iii), parece tersido efetivo o programa de capacitação laboral? Que faria com que nossa conclusão fosse mais convincente?
